# Generated by Django 4.0.6 on 2022-08-10 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_rating', models.CharField(max_length=5, verbose_name='Age Rating')),
                ('age_rating_guide', models.CharField(max_length=50, verbose_name='Age Rating Guidence')),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Average Rating')),
                ('description', models.TextField(verbose_name='Description')),
                ('episode_count', models.IntegerField(verbose_name='Episodes count')),
                ('episode_length', models.IntegerField(verbose_name='Episode length')),
                ('kind', models.CharField(max_length=10, verbose_name='Show Type')),
                ('poster_image', models.URLField(max_length=255, verbose_name='Poster URL')),
                ('season', models.CharField(max_length=20, null=True, verbose_name='Realese season')),
                ('staff', models.TextField(null=True, verbose_name='Staff Team')),
                ('studio', models.CharField(max_length=50, null=True, verbose_name='Studio')),
                ('tags', models.TextField(null=True, verbose_name='Genres Tags')),
                ('title', models.CharField(max_length=255, verbose_name='English title')),
                ('title_jp', models.CharField(max_length=255, verbose_name='Japan title')),
                ('total_length', models.IntegerField(verbose_name='Total length')),
                ('voice_actors', models.TextField(null=True, verbose_name='Voice Actors')),
                ('year', models.IntegerField(null=True, verbose_name='Release year')),
                ('year_end', models.IntegerField(null=True, verbose_name='Airing end year')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rating star',
                'verbose_name_plural': 'Rating stars',
            },
        ),
        migrations.CreateModel(
            name='UserAnimeLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watching', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('on_hold', models.BooleanField(default=False)),
                ('dropped', models.BooleanField(default=False)),
                ('plan_to_watch', models.BooleanField(default=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anidb.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=5000, verbose_name='Review')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anidb.anime', verbose_name='Anime')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anidb.reviews', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anidb.anime', verbose_name='anime')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anidb.ratingstar', verbose_name='star')),
            ],
            options={
                'verbose_name': 'Users rating',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
