# Generated by Django 4.0.6 on 2022-07-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anidb', '0002_rename_show_type_anime_kind_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='title_en',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='title_ja_jp',
            new_name='title_jp',
        ),
    ]
