# Generated by Django 4.0.6 on 2022-08-08 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anidb', '0003_rename_title_en_anime_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnimeLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watching', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('on_hold', models.BooleanField(default=False)),
                ('dropped', models.BooleanField(default=False)),
                ('plan_to_watch', models.BooleanField(default=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anidb.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
