# Generated by Django 4.0.6 on 2022-09-01 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime_db', '0001_initial'),
        ('manga_db', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='anime',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='anime_review', to='anime_db.anime'),
        ),
        migrations.AlterField(
            model_name='review',
            name='manga',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manga_review', to='manga_db.manga'),
        ),
    ]
