# Generated by Django 4.0.6 on 2022-09-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_review_anime_alter_review_manga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='votes_down',
            new_name='votes_down_count',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='votes_up',
            new_name='votes_up_count',
        ),
    ]
