version: "3.9"

services:
  db:
    image: postgres:13.7-alpine
    container_name: general_db
    volumes:
      - docker_postgres_vol:/var/lib/postgresql/data
    env_file:
      - docker.env
    ports: 
      - "5434:5432"
    
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    depends_on:
      - db
  

  db_pgadmin:
    image: dpage/pgadmin4
    container_name: general_db_admin
    env_file:
      - docker.env
    ports:
      - "5050:80"
    volumes:
      - docker_my_pgadmin:/var/lib/pgadmin
    depends_on:
      - db
  
  


volumes:
  docker_postgres_vol:
    external: true
  docker_my_pgadmin:
    external: true
  
