FROM postgres:13.7-alpine

COPY ./csv/anime_main_table.csv /data/anime_main_table.csv
COPY ./csv/genres_tags.csv /data/genres_tags.csv
COPY ./csv/release_info.csv /data/release_info.csv
COPY ./csv/additional_info.csv /data/additional_info.csv