version: "3.7"

services:
  postgres_db:
    build:
      dockerfile: ./Dockerfile
      context: '.'
    container_name: postgres_dev
    env_file:
      - ../.env
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    ports: 
      - "5434:5432"

  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    env_file:
      - ../.env
    ports:
      - "5050:80"
    volumes:
      - my_pgadmin:/var/lib/pgadmin

volumes:
  postgres_vol:
  my_pgadmin:
