# Generated by Django 4.0.6 on 2022-07-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birhdate',
            field=models.DateTimeField(help_text='User birthday', null=True),
        ),
    ]
