# Generated by Django 4.0.6 on 2022-09-14 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.TextField(verbose_name='Manga Author')),
                ('average_rating', models.FloatField(verbose_name='Average Rating')),
                ('chapters', models.PositiveIntegerField(verbose_name='Chapters count')),
                ('description', models.TextField(verbose_name='Description')),
                ('media_type', models.CharField(max_length=20)),
                ('picture_main', models.URLField(max_length=255, verbose_name='Poster URL')),
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('On Hiatus', 'On Hiatus'), ('Publishing', 'Publishing'), ('Discontinued', 'Discontinued')], max_length=20)),
                ('tags', models.TextField(null=True, verbose_name='Genres Tags')),
                ('title', models.CharField(max_length=255, verbose_name='English title')),
                ('title_jp', models.CharField(max_length=255, verbose_name='Japan title')),
                ('volumes', models.PositiveIntegerField(verbose_name='Volumes count')),
                ('year_end', models.DateTimeField(null=True, verbose_name='End year')),
                ('year_start', models.DateTimeField(null=True, verbose_name='Start year')),
                ('user_favorites_anime', models.ManyToManyField(blank=True, related_name='user_favorites_manga', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
