# Generated by Django 4.0.6 on 2022-09-16 13:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.TextField(verbose_name='Manga Author')),
                ('average_rating', models.FloatField(verbose_name='Average Rating')),
                ('chapters', models.PositiveIntegerField(verbose_name='Chapters count')),
                ('description', models.TextField(verbose_name='Description')),
                ('media_type', models.CharField(max_length=20)),
                ('picture_main', models.URLField(max_length=255, verbose_name='Poster URL')),
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('On Hiatus', 'On Hiatus'), ('Publishing', 'Publishing'), ('Discontinued', 'Discontinued')], max_length=20)),
                ('tags', models.TextField(null=True, verbose_name='Genres Tags')),
                ('title', models.CharField(max_length=255, verbose_name='English title')),
                ('title_jp', models.CharField(max_length=255, verbose_name='Japan title')),
                ('volumes', models.PositiveIntegerField(verbose_name='Volumes count')),
                ('year_end', models.DateTimeField(null=True, verbose_name='End year')),
                ('year_start', models.DateTimeField(null=True, verbose_name='Start year')),
                ('user_favorites', models.ManyToManyField(blank=True, related_name='favorites_manga', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manga',
                'verbose_name_plural': 'Manga',
            },
        ),
        migrations.CreateModel(
            name='MyMangaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(choices=[(0, 'Not Rated'), (1, 'Awful'), (2, 'Pretty Bad'), (3, 'So So'), (4, 'Good'), (5, 'Masterpiece')], default=0, verbose_name='Item score in list')),
                ('note', models.TextField(max_length=300, verbose_name='My note about item')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Reading', 'Reading'), ('Plan to read', 'Plat To Read'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], max_length=15)),
                ('num_chapters_read', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7774)], verbose_name='Number of readed chapters')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga_db.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MangaReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.review')),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manga_review', to='manga_db.manga')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity.review',),
        ),
    ]
