# Generated by Django 4.0.6 on 2022-09-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(verbose_name='Average Rating')),
                ('description', models.TextField(verbose_name='Description')),
                ('title', models.CharField(max_length=255, verbose_name='English title')),
                ('title_jp', models.CharField(max_length=255, verbose_name='Japan title')),
                ('picture_main', models.URLField(max_length=255, verbose_name='Poster URL')),
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('On Hiatus', 'On Hiatus'), ('Publishing', 'Publishing')], max_length=10)),
                ('volumes', models.PositiveIntegerField()),
                ('chapters', models.PositiveIntegerField()),
                ('year_start', models.IntegerField(null=True, verbose_name='Start year')),
                ('genre', models.CharField(max_length=15, verbose_name='Essential genre')),
            ],
        ),
    ]
