# Generated by Django 4.0.6 on 2022-09-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='user_favorites_anime',
            new_name='user_favorites',
        ),
    ]
