# Generated by Django 4.0.6 on 2022-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('On Hiatus', 'On Hiatus'), ('Publishing', 'Publishing'), ('Discontinued', 'Discontinued')], max_length=20),
        ),
    ]
