# Generated by Django 4.0.6 on 2022-09-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_db', '0002_alter_mymangalist_num_chapters_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymangalist',
            old_name='num_chapters_read',
            new_name='num_chapters_readed',
        ),
    ]
