# Generated by Django 4.0.6 on 2022-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_db', '0002_alter_manga_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.TextField(verbose_name='Manga Author'),
        ),
    ]
