# Generated by Django 4.0.6 on 2022-09-14 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga_db', '0002_rename_user_favorites_anime_manga_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='user_favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites_manga', to=settings.AUTH_USER_MODEL),
        ),
    ]
