# Generated by Django 4.0.6 on 2022-09-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_db', '0003_rename_num_chapters_read_mymangalist_num_chapters_readed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymangalist',
            options={'verbose_name_plural': 'MyManga list'},
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='picture_main',
            new_name='poster_image',
        ),
    ]
