# Generated by Django 4.0.6 on 2022-08-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='object_id',
            new_name='commentable_id',
        ),
    ]
