# Generated by Django 4.0.6 on 2022-08-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_activity', '0002_rename_object_id_comment_commentable_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user_id',
        ),
    ]
