# Generated by Django 4.0.6 on 2022-07-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_rating', models.CharField(max_length=5, verbose_name='Age Rating')),
                ('age_rating_guide', models.CharField(max_length=50, verbose_name='Age Rating Guidence')),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Average Rating')),
                ('description', models.TextField(verbose_name='Description')),
                ('episode_count', models.IntegerField(verbose_name='Episodes count')),
                ('episode_length', models.IntegerField(verbose_name='Episode length')),
                ('poster_image', models.URLField(max_length=255, verbose_name='Poster URL')),
                ('release_end_year', models.IntegerField(null=True, verbose_name='Airing end year')),
                ('release_season', models.CharField(max_length=20, null=True, verbose_name='Realese season')),
                ('release_start_year', models.IntegerField(null=True, verbose_name='Release year')),
                ('show_type', models.CharField(max_length=10, verbose_name='Show Type')),
                ('staff', models.TextField(verbose_name='Staff Team')),
                ('studio', models.CharField(max_length=50, verbose_name='Studio')),
                ('tags', models.TextField(null=True, verbose_name='Genres Tags')),
                ('title_en', models.CharField(max_length=255, verbose_name='English title')),
                ('title_ja_jp', models.CharField(max_length=255, verbose_name='Japan title')),
                ('total_length', models.IntegerField(verbose_name='Total length')),
                ('voice_actors', models.TextField(verbose_name='Voice Actors')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
            },
        ),
    ]
