# Generated by Django 4.0.6 on 2022-07-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_rating', models.CharField(max_length=5, verbose_name='Age Rating')),
                ('age_rating_guide', models.CharField(max_length=50, verbose_name='Age Rating Guidence')),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Average Rating')),
                ('description', models.TextField(verbose_name='Description')),
                ('episode_count', models.IntegerField(verbose_name='Episodes count')),
                ('episode_length', models.IntegerField(verbose_name='Episode length')),
                ('poster_image', models.URLField(max_length=255, verbose_name='Poster URL')),
                ('show_type', models.CharField(max_length=10, verbose_name='Show Type')),
                ('title_en', models.CharField(max_length=255, verbose_name='English title')),
                ('title_ja_jp', models.CharField(max_length=255, verbose_name='Japan title')),
                ('total_length', models.IntegerField(verbose_name='Total length')),
            ],
            options={
                'verbose_name': 'Anime Title',
                'verbose_name_plural': 'Anime Titles',
            },
        ),
        migrations.CreateModel(
            name='ReleaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(null=True, verbose_name='Airing end year')),
                ('title_en', models.CharField(max_length=255, verbose_name='English title')),
                ('season', models.CharField(max_length=255, null=True, verbose_name='Realese season')),
                ('release_year', models.IntegerField(null=True, verbose_name='Release year')),
                ('tags', models.TextField(verbose_name='Genres Tags')),
                ('release_info', models.ManyToManyField(related_name='release_info', to='database.anime', verbose_name='Release Info')),
            ],
            options={
                'verbose_name': 'Release Info',
            },
        ),
    ]
