# Generated by Django 4.0.6 on 2022-07-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.CharField(max_length=50, null=True, verbose_name='Studio'),
        ),
    ]
