# Generated by Django 4.0.6 on 2022-07-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_anime_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='voice_actors',
            field=models.TextField(null=True, verbose_name='Voice Actors'),
        ),
    ]
