# Generated by Django 4.0.6 on 2022-07-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('age_rating', models.CharField(max_length=5, verbose_name='Age Rating')),
                ('age_rating_guide', models.CharField(max_length=50, verbose_name='Age Rating Guidence')),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Average Rating')),
                ('description', models.TextField(verbose_name='Description')),
                ('episode_count', models.IntegerField(verbose_name='Episodes count')),
                ('episode_length', models.IntegerField(verbose_name='Episode length')),
                ('poster_image', models.URLField(max_length=255, verbose_name='Poster URL')),
                ('show_type', models.CharField(max_length=10, verbose_name='Show Type')),
                ('title_en', models.CharField(max_length=255, verbose_name='English title')),
                ('title_ja_jp', models.CharField(max_length=255, verbose_name='Japan title')),
                ('total_length', models.IntegerField(verbose_name='Total length')),
            ],
            options={
                'verbose_name': 'Anime Title',
                'verbose_name_plural': 'Anime Titles',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Genre name')),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rating star',
                'verbose_name_plural': 'Rating stars',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=5000, verbose_name='Review')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_db.anime', verbose_name='Anime')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anime_db.reviews', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='AverageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_db.anime', verbose_name='anime')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_db.ratingstar', verbose_name='star')),
            ],
            options={
                'verbose_name': 'Average score',
                'verbose_name_plural': 'Average scores',
            },
        ),
    ]
