# Generated by Django 4.0.6 on 2022-09-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='Release year'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year_end',
            field=models.PositiveIntegerField(null=True, verbose_name='Airing end year'),
        ),
    ]
