# Generated by Django 4.0.6 on 2022-07-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='_id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='anime',
            name='age_rating',
            field=models.CharField(max_length=50, verbose_name='Age Rating'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='total_length',
            field=models.CharField(max_length=255, verbose_name='Total length'),
        ),
    ]
