# Generated by Django 4.0.6 on 2022-09-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_db', '0002_alter_myanimelist_num_episodes_watched'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myanimelist',
            options={'verbose_name_plural': 'MyAnime list'},
        ),
    ]
