# Generated by Django 4.0.6 on 2022-07-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_db', '0002_alter_genrestaglist_genres_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrestaglist',
            name='genres_tags',
            field=models.TextField(null=True),
        ),
    ]
