# Generated by Django 4.0.6 on 2022-09-14 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime_db', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='user_favorites_anime',
        ),
        migrations.AddField(
            model_name='anime',
            name='user_favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites_anime', to=settings.AUTH_USER_MODEL),
        ),
    ]
