# Generated by Django 4.0.6 on 2022-08-19 22:00

import apps.authentication.utils.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_options_customuser_auth_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_online_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='media/user_avatar/default', null=True, upload_to=apps.authentication.utils.utils.get_path_upload_avatar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
