# Generated by Django 4.0.6 on 2022-08-24 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customuser_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birhdate',
            new_name='birthdate',
        ),
    ]
