# Generated by Django 4.0.6 on 2022-08-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_birhdate_customuser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(help_text='User birthdate', null=True),
        ),
    ]
